<a href="https://colab.research.google.com/github/savioursho/data-analysis/blob/main/pca_em.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [32]:
# 元の行列
missing_matrix = np.array(
    [[1, 2],
     [2, np.nan]]
)
missing_matrix

array([[ 1.,  2.],
       [ 2., nan]])

In [33]:
# 欠損値があるところのマスク
mask = np.isnan(missing_matrix)
mask

array([[False, False],
       [False,  True]])

In [34]:
# 列の平均で欠損を埋める
initialized_matrix = missing_matrix.copy()
initialized_matrix[1, 1] = 2
last_projection = initialized_matrix
initialized_matrix

array([[1., 2.],
       [2., 2.]])

イテレーション1

In [31]:
def iteration(matrix, projection, mask):
    last_projection = projection.copy()

    # 行列分解してランク1にする
    u, s, vh = np.linalg.svd(matrix)
    projection = u[:, 0].reshape(2, 1) * s[0] @ vh[0, :].reshape(1, 2)

    # 欠損値部分を置き換え
    matrix[mask] = projection[mask]

    # 欠損部分の差を計算
    delta = last_projection[mask] - projection[mask]
    diff = np.square(delta).sum() / np.square(projection[mask]).sum()

    return matrix, projection, diff

In [39]:
matrix = initialized_matrix
projection = initialized_matrix
for i in range(100):
    matrix, projection, diff = iteration(matrix, projection, mask)
    if i % 10 == 0:
        print("iter:\t", i)
        print("diff:\t", diff)
        print("matrix:\t\n", matrix)

iter:	 0
diff:	 4.2634996620823475e-06
matrix:	
 [[1.         2.        ]
 [2.         3.82687031]]
iter:	 10
diff:	 1.611451054315454e-06
matrix:	
 [[1.         2.        ]
 [2.         3.88827814]]
iter:	 20
diff:	 6.45190832207753e-07
matrix:	
 [[1.        2.       ]
 [2.        3.9271256]]
iter:	 30
diff:	 2.675875051150114e-07
matrix:	
 [[1.         2.        ]
 [2.         3.95214559]]
iter:	 40
diff:	 1.1347263041532632e-07
matrix:	
 [[1.         2.        ]
 [2.         3.96844088]]
iter:	 50
diff:	 4.881035792963858e-08
matrix:	
 [[1.        2.       ]
 [2.        3.9791297]]
iter:	 60
diff:	 2.1191389790631107e-08
matrix:	
 [[1.         2.        ]
 [2.         3.98617335]]
iter:	 70
diff:	 9.256444065241534e-09
matrix:	
 [[1.         2.        ]
 [2.         3.99082891]]
iter:	 80
diff:	 4.059430021842469e-09
matrix:	
 [[1.         2.        ]
 [2.         3.99391214]]
iter:	 90
diff:	 1.7849771464349408e-09
matrix:	
 [[1.         2.        ]
 [2.         3.99595672]]
